---
- name: Import Centos Official (workaround for https://bugzilla.redhat.com/show_bug.cgi?id=2184640)
  ansible.builtin.rpm_key:
    state: present
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution'] == "CentOS"
  tags:
    - installation-redhat

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - haproxy
    - keepalived
  tags:
    - installation